#!/usr/bin/env node

var url = require('url');
var Promise = require('promise');

var config = require('../lib/config');
var app = require('../lib/app');

var instance = app(config);

instance.on('ready', reset);

function reset() {
  console.log('Resetting...');

  var pending = instance.purgePendingArticles();

  Promise.all([pending])
    .then(onComplete);

  function onComplete() {
    console.log('Articles, article queue, and votes have been reset.');
    process.exit();
  }
}
